### ISSUE TITLE
About Docker  ->step 4. Start the docker containe 

### ISSUE THREAD

**Issue by FrankLinxzx** [tom-doerr/TecoGAN#9]
i use win10 computer
step 3. install is ok
4. Start the docker container we just build
docker run --gpus all -it --mount src=$(pwd),target=/TecoGAN,type=bind -w /TecoGAN tecogan_image bash
i dont know how to use this ,type in cmd and shows 

docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '$(pwd)' mount path must be absolute.
See 'docker run --help'.

may someone can tell me how to do thx

**Comment by tom-doerr** [comment]
You could try to use the Windows Subsystem for Linux with Ubuntu to run it,

**Comment by FrankLinxzx** [comment]
> You could try to use the Windows Subsystem for Linux with Ubuntu to run it,

ok thx bro  i try it

**Comment by FrankLinxzx** [comment]
> You could try to use the Windows Subsystem for Linux with Ubuntu to run it,

excuse me if i use python runGan.py 3
and it show  
Preparing train_data
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    rdata = frvsr_gpu_data_loader(FLAGS, useValidat)
  File "C:\Users\f2001\TecoGAN\lib\dataloader.py", line 289, in frvsr_gpu_data_loader
    batch_list, num_image_list_HR_t_cur = loadHRfunc(FLAGS, tar_size)
  File "C:\Users\f2001\TecoGAN\lib\dataloader.py", line 179, in loadHR
    raise ValueError('Video input directory not found')
ValueError: Video input directory not found

is that i have to add code behind python runGan.py 3 ?  sorry for my idiot question

**Comment by tom-doerr** [comment]
No you don't. This seems to be a Windows related issue, the program probably can't deal with the Windows path format.
There's a another issue open for this in the original TecoGAN repo, you could ask there if anybody managed to solve the issue: https://github.com/thunil/TecoGAN/issues/85 .
If that doesn't work, you could use a Linux VM to run it.

**Comment by FrankLinxzx** [comment]
> No you don't. This seems to be a Windows related issue, the program probably can't deal with the Windows path format.
> There's a another issue open for this in the original TecoGAN repo, you could ask there if anybody managed to solve the issue: [thunil/TecoGAN#85](https://github.com/thunil/TecoGAN/issues/85) .
> If that doesn't work, you could use a Linux VM to run it.

OK THX  i will try to install Linux later

**Comment by FrankLinxzx** [comment]
> No you don't. This seems to be a Windows related issue, the program probably can't deal with the Windows path format.
> There's a another issue open for this in the original TecoGAN repo, you could ask there if anybody managed to solve the issue: [thunil/TecoGAN#85](https://github.com/thunil/TecoGAN/issues/85) .
> If that doesn't work, you could use a Linux VM to run it.

same problem cant find the dir  

 line 289, in frvsr_gpu_data_loader
batch_list, num_image_list_HR_t_cur = loadHRfunc(FLAGS, tar_size)
 line 179, in loadHR
raise ValueError('Video input directory not found')
ValueError: Video input directory not found

sad
on Ubuntu 18.04.

**Comment by tom-doerr** [comment]
That's strange. Did you do a fresh clone of the repo and do all the installation steps after downloading Ubuntu?

**Comment by FrankLinxzx** [comment]
> That's strange. Did you do a fresh clone of the repo and do all the installation steps after downloading Ubuntu?

sorry  i just use older one not docker version cause i really dont know how docker how to use

**Comment by tom-doerr** [comment]
Yeah it's a bit of work figuring out how docker works.
However it's probably much easier for you to figure out how to set it up using docker then installing it without it.

**Comment by FrankLinxzx** [comment]
ok i'll try docker on ubuntu later
